from pathlib import Path
p=Path('tools/vercel-whatsapp-worker.mjs')
s=p.read_text()
s=s.replace("import whatsappWebJs from 'whatsapp-web.js';", "import whatsappWebJs from 'whatsapp-web.js';\nimport { createLearningStore, inferLearningIntent } from './learning-engine.mjs';")
s=s.replace("const auditFile = path.join(clientDir, 'audit.jsonl');", "const auditFile = path.join(clientDir, 'audit.jsonl');\nconst groupKnowledgeFile = path.join(clientDir, 'group-knowledge.json');\nconst learningHistoryFile = path.join(clientDir, 'learning-history.jsonl');\nconst learningIndexFile = path.join(clientDir, 'learning-index.json');")
s=s.replace("const processedMessageIds = new Map();", "const processedMessageIds = new Map();\nconst lastInboundByGroup = new Map();\nconst botReplyFingerprints = new Map();\nconst learningStore = createLearningStore({ knowledgeFile: groupKnowledgeFile, historyFile: learningHistoryFile, indexFile: learningIndexFile });")
s=s.replace("const addGroup = (id, name) => {", "const addGroup = (id, name, description = '') => {")
s=s.replace("name: String(name || previousRegistry[id]?.name || 'Grupo do WhatsApp'),\n        lastSeenAt", "name: String(name || previousRegistry[id]?.name || 'Grupo do WhatsApp'),\n        description: String(description || ''),\n        lastSeenAt")
s=s.replace("addGroup(id, chat?.name || chat?.formattedTitle);", "addGroup(id, chat?.name || chat?.formattedTitle, chat?.description || chat?.groupMetadata?.desc || '');")
s=s.replace("await writeJson(registryFile, nextRegistry);\n\n      const validAllowed", "await writeJson(registryFile, nextRegistry);\n      for (const group of discovered.values()) await learningStore.syncGroup({ groupId: group.id, name: group.name, description: group.description || '' });\n\n      const validAllowed")
s=s.replace("async function replyAndRemember(msg, groupName, incomingText, reply, meta = {}) {\n  await msg.reply(reply);", "async function replyAndRemember(msg, groupName, incomingText, reply, meta = {}) {\n  botReplyFingerprints.set(`${msg.from}|${normalizeForIntent(reply)}`, Date.now());\n  await msg.reply(reply);")
s=s.replace("logEvent('message', `${groupName}: ${readableText}`, { groupId: msg.from, author });", "logEvent('message', `${groupName}: ${readableText}`, { groupId: msg.from, author });\n    lastInboundByGroup.set(msg.from, { text: readableText, at: Date.now() });\n    void learningStore.append({ groupId: msg.from, groupName, direction: 'incoming', source: 'live', text: readableText, intent: inferLearningIntent(readableText) });")
p.write_text(s)
print('ok')
# trigger workflow
